FROM ruby:2.6.3

LABEL maintainer="Sokly <sokly@instedd.org>"

RUN curl -sL https://deb.nodesource.com/setup_10.x  | bash -

RUN apt-get update -qq && \
  apt-get install -y vim nodejs postgresql-client && \
  apt-get clean && \
  npm install -g yarn && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app

RUN gem install bundler -v 2.0.2

COPY Gemfile* /app/
RUN bundle install

# Install yarn packages
COPY package.json yarn.lock /app/
RUN yarn install --check-files

COPY . /app
