development: &default
  host: <%= ENV.fetch('ELASTICSEARCH_URL') { 'http://localhost:9200' } %>
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
